version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
    commands:
      - pip install awscli --upgrade --quiet
      - pip install cfn-lint --quiet              
  build:
    commands:
      - cfn-lint ${SAM_TEMPLATE} 
      - cfn-lint -i W -t ${SAM_TEMPLATE}
      - sam validate --template ${SAM_TEMPLATE} 
      - sam build --template ${SAM_TEMPLATE} 
      - sam deploy --stack-name ${ResourcesPrefix}-${Environment}-stack --capabilities CAPABILITY_IAM --region ${TESTING_REGION} --s3-bucket ${TESTING_ARTIFACTS_BUCKET} --no-fail-on-empty-changeset --role-arn ${TESTING_CLOUDFORMATION_EXECUTION_ROLE}  --no-confirm-changeset --parameter-overrides ParameterKey=S3BucketParam,ParameterValue=${TESTING_ARTIFACTS_BUCKET} ParameterKey=ResourcesPrefix,ParameterValue=${ResourcesPrefix} ParameterKey=Environment,ParameterValue=${Environment} ParameterKey=ManagedBy,ParameterValue=${ManagedBy} ParameterKey=CostAllocationProduct,ParameterValue=${CostAllocationProduct} ParameterKey=CampaignARNParam,ParameterValue=${CampaignARNParam} ParameterKey=EventTrackerIdParam,ParameterValue=${EventTrackerIdParam} ParameterKey=ExistingKinesisStreamARN,ParameterValue=${ExistingKinesisStreamARN} 