version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
    commands:
      - pip install awscli --upgrade --quiet
      - pip install cfn-lint --quiet              
  build:
    commands:
      - cfn-lint ${SAM_TEMPLATE} || true
      - sam validate --template ${SAM_TEMPLATE} 
      - sam build --template ${SAM_TEMPLATE} 
      - sam deploy --stack-name features-${CI_COMMIT_REF_NAME}-cfn-stack --capabilities CAPABILITY_IAM --region ${TESTING_REGION} --s3-bucket ${TESTING_ARTIFACTS_BUCKET} --no-fail-on-empty-changeset --role-arn ${TESTING_CLOUDFORMATION_EXECUTION_ROLE}  --no-confirm-changeset